### ISSUE TITLE
Chicago River 2.0 

### ISSUE THREAD

**Issue by fgregg** [open-city/chicago-river-sewage#23]
- [x] Show the specific locations of current CSO outfalls on map. Depends on #6, #7 
- [x] Show historical events #4
- [ ] Let user download historical events
- [ ] Let user download historical water quality measures
- [ ] Let user download historical rain data
- [ ] About page that describes what this is all about, depends on #14, #9
